import = [
  "~/.config/alacritty/tokyonight_moon.toml"
]

[env]
TERM = "alacritty"

[font]
size = 14.0

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[window]
decorations = "None"
startup_mode = "Maximized"
opacity = 0.9
dynamic_padding = true

[window.padding]
x = 8
y = 8

[keyboard]
bindings = [
  { key = "V", mods = "Control", action = "Paste"},
  { key = "Home", chars = "\u001BOH", mode = "AppCursor" },
  { key = "Home", chars = "\u001B[H", mode = "~AppCursor" },
  { key = "End", chars = "\u001BOF", mode = "AppCursor" },
  { key = "End", chars = "\u001B[F", mode = "~AppCursor" }
]

